Added remain Maven API, update test
hkarthik7/azure-devops-java-sdk pull request #22
Opened 2022-05-18 13:04 UTC by shblue21

# Azure DevOps java sdk pull request template guide

Thank you for your interest in contributing to this project.

## Description

I implemented the remaining maven api. (Excluding download). Test was implemented for all cases, and the entire test function was also written.

## PR Checklist

- [ ] Added help
- [x] Added unit test/s
- [ ] Updated Change log

2022-05-18 13:48 UTC, hkarthik7 requested changes
Here are the test failure messages:

[ERROR]   MavenApiTest.shouldGetPackageVersion:63 expected:<org.[HelloWorld:HelloW]orld> but was:<org.[helloworld:hellow]orld>
[ERROR]   MavenApiTest.shouldGetPackageVersionWithQueryParameters:72 expected:<org.[HelloWorld:HelloW]orld> but was:<org.[helloworld:hellow]orld>

2022-05-18 14:56 UTC, hkarthik7 commented
@shblue21 no luck mate. Worth updating the tests once and then give it a try.

2022-05-19 09:23 UTC, shblue21 commented
@hkarthik7 First of all, sorry for generating a lot of release pipeline logs.
I modified the test code and created an example document.
Please let me know if you need to edit the test. (Delete sysout, etc.)

2022-05-19 09:24 UTC, shblue21 commented
And I can't implement DownloadPackage right away. Because

2022-05-20 08:38 UTC, hkarthik7 commented
**@shblue21** The download functionality has to be tested intensely before applying. We should think a way to introduce this without affecting the core functionality of SDK. After all we've built this for our use and can come up with a way that works for everyone. Since few projects depends on the SDK for Azure DevOps integration I would recommend to add the `download package` functionality later.

You can write an exact API wrapper for `downloadPackage` and create a helper method that calls `downloadPackage` to actually download the contents in a `.zip` or any format that makes sense.

[Description from documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/maven/download-package?view=azure-devops-rest-7.1)  - 
*Fulfills Maven package file download requests by either returning the URL of the requested package file or, in the case of Azure DevOps Server (OnPrem), returning the content as a stream.*

I did a quick test from Postman and the response was a stream content.

So, you can create a method `downlodPackage` that returns file stream. Then create a helper method something like `downloadPackageContent` and ask the user to choose the file format. It can be a text, json, .md, .zip etc, because it expected that user should be aware of file format they're requesting for. An example logic shown [here](https://stackoverflow.com/questions/27641774/how-to-download-zip-file-from-url-using-java)

2022-05-20 09:44 UTC, hkarthik7 reviewed
LGTM

2022-05-22 04:11 UTC, shblue21 commented on azd/src/main/java/org/azd/maven/MavenApi.java
>              throws AzDException {
As you know, you can create a Custom View type in Azure Devops.

2022-05-25 08:53 UTC, hkarthik7 approved these changes
LGTM

2022-05-25 08:53 UTC, merged

2022-05-25 08:53 UTC, hkarthik7 commented
Happy to do a squash merge.

2022-05-25 09:03 UTC, shblue21 commented
Thanks for merging!

2022-07-20 16:57 UTC, hkarthik7 commented
@shblue21, I've modified the `downloadPackage` method in **MavenApi**. Please take a look and test it, if the implementation is not what you're looking for or you didn't like please feel free to modify it.

2022-07-21 12:25 UTC, shblue21 commented
@hkarthik7   mate. I'll check right away. thank you very much.

2022-07-31 09:44 UTC, shblue21 commented
@hkarthik7  It seems to be working fine.

2022-08-25 02:24 UTC, shblue21 commented
@hkarthik7 I want to implement uploadPackage. 
The request url has the following format:  
PUT pkgs.dev.azure.com/{account}/{org}/**_packaging**/{feed}/maven/v1/{artifactid}/{groupid}/{version}/{filename}  

But the corresponding url for API_RELATIVE_PATH is _packaging .
Is there any way to implement this by changing API_RELATIVE_PATH ?


```java
public final class RestClientProvider extends BaseRestClient {
    protected static final JsonMapper MAPPER = new JsonMapper();
    private static final String API_RELATIVE_PATH = "_apis";
```

2022-08-25 04:19 UTC, hkarthik7 commented
@shblue21, please implement what makes sense to you. I don’t recommend modifying the existing relative path property as it will change the entire functionality of the library. You can do something like creating a string build to construct the url and call RestClient.send() that demands a request url.